{
    album:
    {
        album_type: 'single',
            artists: [[Object]],
                available_markets:
        ['AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'],
            external_urls:
        { spotify: 'https://open.spotify.com/album/65siSh34OjZPMx0obk0YRj' },
        href: 'https://api.spotify.com/v1/albums/65siSh34OjZPMx0obk0YRj',
            id: '65siSh34OjZPMx0obk0YRj',
                images: [[Object], [Object], [Object]],
                    name: 'Patience',
                        release_date: '2019-03-22',
                            release_date_precision: 'day',
                                total_tracks: 1,
                                    type: 'album',
                                        uri: 'spotify:album:65siSh34OjZPMx0obk0YRj'
    },
    artists:
    [{
        external_urls: [Object],
        href: 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb',
        id: '5INjqkS1o8h1imAzPqGZBb',
        name: 'Tame Impala',
        type: 'artist',
        uri: 'spotify:artist:5INjqkS1o8h1imAzPqGZBb'
    }],
        available_markets:
    ['AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA'],
        disc_number: 1,
            duration_ms: 292267,
                explicit: false,
                    external_ids: { isrc: 'AUUM71900284' },
    external_urls:
    { spotify: 'https://open.spotify.com/track/2drEUEg0TYQR6dDEHkpuPE' },
    href: 'https://api.spotify.com/v1/tracks/2drEUEg0TYQR6dDEHkpuPE',
        id: '2drEUEg0TYQR6dDEHkpuPE',
            is_local: false,
                name: 'Patience',
                    popularity: 74,
                        preview_url: null,
                            track_number: 1,
                                type: 'track',
                                    uri: 'spotify:track:2drEUEg0TYQR6dDEHkpuPE'
}